# Generated by Django 5.0.2 on 2024-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student', to='studentapi.course'),
        ),
    ]
